# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-02-03 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MilitaryShow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KGStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromId', models.CharField(max_length=20, verbose_name='关系起始')),
                ('rel', models.CharField(max_length=20, verbose_name='关系')),
                ('toId', models.CharField(max_length=20, verbose_name='关系终止')),
            ],
        ),
    ]
